services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672" # AMQP port for client connections
      - "15672:15672" # Management UI[](http://localhost:15672)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    # Automatically declare the sendEmail topic exchange when RabbitMQ starts
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    restart: unless-stopped
    networks:
      - hrms-network

  postgres:
    image: postgres:15.15-alpine3.23
    container_name: postgres_container
    environment:
      POSTGRES_DB: hrms
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: root_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hrms-network

volumes:
  postgres_data:

networks:
  hrms-network:
    driver: bridge
    name: hrms-network
