spring:
  application:
    name: hrms
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: false # Tạm thời tắt Flyway để tránh xung đột với ddl-auto: update
server:
  port: 8080
  #servlet:
   # context-path: /api

# Logging
logging:
  level:
    org.httt2.hrms: DEBUG
    org.hibernate.SQL: DEBUG

application:
  security:
    jwt:
      # This looks for the JWT_SECRET env var.
      # It must be at least 256-bit (32 characters+).
      secret-key: ${JWT_SECRET}

      # Expiration time in milliseconds.
      # Default: 86400000 (1 day) if not provided in env.
      expiration: ${JWT_EXPIRATION:86400000} # 1 day

# Config AWS S3
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:AKIA_TEST_KEY}       # Thay bằng key thật sau này
  secretKey: ${AWS_SECRET_ACCESS_KEY:SECRET_TEST_KEY}   # Thay bằng key thật sau này
  region: ap-southeast-1
  s3:
    bucket: htt2-hrms-bucket