spring:
  application:
    name: hrms
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.htt2.hrms: DEBUG
    org.hibernate.SQL: DEBUG

