CREATE TABLE bank_account
(
    account_number VARCHAR(255) NOT NULL,
    bank_name      VARCHAR(255) NOT NULL,
    account_name   VARCHAR(255),
    emp_id         BIGINT       NOT NULL,
    CONSTRAINT pk_bank_account PRIMARY KEY (account_number, bank_name)
);

CREATE TABLE bonus_point_account
(
    emp_id      BIGINT NOT NULL,
    bonus_point INTEGER,
    CONSTRAINT pk_bonus_point_account PRIMARY KEY (emp_id)
);

CREATE TABLE campaign
(
    campaign_id    BIGINT NOT NULL,
    campaign_name  VARCHAR(255),
    campaign_type  VARCHAR(255),
    primary_metric VARCHAR(255),
    description    VARCHAR(255),
    start_date     date,
    end_date       date,
    CONSTRAINT pk_campaign PRIMARY KEY (campaign_id)
);

CREATE TABLE campaign_participant
(
    joined_at   TIMESTAMP WITHOUT TIME ZONE,
    emp_id      BIGINT NOT NULL,
    campaign_id BIGINT NOT NULL,
    CONSTRAINT pk_campaign_participant PRIMARY KEY (emp_id, campaign_id)
);

CREATE TABLE department
(
    dept_id    BIGINT       NOT NULL,
    dept_name  VARCHAR(255) NOT NULL,
    location   VARCHAR(255),
    manager_id BIGINT,
    CONSTRAINT pk_department PRIMARY KEY (dept_id)
);

CREATE TABLE education
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    degree         VARCHAR(255)                            NOT NULL,
    field_of_study VARCHAR(255),
    gpa            DOUBLE PRECISION,
    country        VARCHAR(255),
    emp_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_education PRIMARY KEY (id)
);

CREATE TABLE employee
(
    emp_id            BIGINT       NOT NULL,
    full_name         VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    phone_number      VARCHAR(255),
    permanent_address VARCHAR(255),
    current_address   VARCHAR(255),
    start_date        date,
    job_level         VARCHAR(255),
    employee_type     VARCHAR(255),
    time_type         VARCHAR(255),
    dept_id           BIGINT,
    position_id       BIGINT,
    manager_id        BIGINT,
    CONSTRAINT pk_employee PRIMARY KEY (emp_id)
);

CREATE TABLE employee_activity
(
    activity_id   BIGINT NOT NULL,
    activity_date date,
    metrics       VARCHAR(255),
    proof_image   VARCHAR(255),
    status        VARCHAR(255),
    emp_id        BIGINT NOT NULL,
    campaign_id   BIGINT NOT NULL,
    CONSTRAINT pk_employee_activity PRIMARY KEY (activity_id)
);

CREATE TABLE position
(
    position_id   BIGINT       NOT NULL,
    position_name VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    salary        DECIMAL      NOT NULL,
    CONSTRAINT pk_position PRIMARY KEY (position_id)
);

CREATE TABLE redemption_transaction
(
    redemption_id   BIGINT NOT NULL,
    converted_point INTEGER,
    amount_received DECIMAL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    emp_id          BIGINT,
    CONSTRAINT pk_redemption_transaction PRIMARY KEY (redemption_id)
);

CREATE TABLE request
(
    request_id   BIGINT       NOT NULL,
    request_type VARCHAR(255) NOT NULL,
    start_date   date,
    end_date     date,
    reason       VARCHAR(255),
    status       VARCHAR(255),
    requester_id BIGINT       NOT NULL,
    approver_id  BIGINT,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

CREATE TABLE transfer_transaction
(
    transfer_id  BIGINT NOT NULL,
    number_point INTEGER,
    note         VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    sender_id    BIGINT,
    receiver_id  BIGINT,
    CONSTRAINT pk_transfer_transaction PRIMARY KEY (transfer_id)
);

ALTER TABLE department
    ADD CONSTRAINT uc_department_manager UNIQUE (manager_id);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_email UNIQUE (email);

ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANK_ACCOUNT_ON_EMP FOREIGN KEY (emp_id) REFERENCES employee (emp_id);

ALTER TABLE bonus_point_account
    ADD CONSTRAINT FK_BONUS_POINT_ACCOUNT_ON_EMP FOREIGN KEY (emp_id) REFERENCES employee (emp_id);

ALTER TABLE campaign_participant
    ADD CONSTRAINT FK_CAMPAIGN_PARTICIPANT_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaign (campaign_id);

ALTER TABLE campaign_participant
    ADD CONSTRAINT FK_CAMPAIGN_PARTICIPANT_ON_EMP FOREIGN KEY (emp_id) REFERENCES employee (emp_id);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES employee (emp_id);

ALTER TABLE education
    ADD CONSTRAINT FK_EDUCATION_ON_EMP FOREIGN KEY (emp_id) REFERENCES employee (emp_id);

ALTER TABLE employee_activity
    ADD CONSTRAINT FK_EMPLOYEE_ACTIVITY_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaign (campaign_id);

ALTER TABLE employee_activity
    ADD CONSTRAINT FK_EMPLOYEE_ACTIVITY_ON_EMP FOREIGN KEY (emp_id) REFERENCES employee (emp_id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_DEPT FOREIGN KEY (dept_id) REFERENCES department (dept_id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES employee (emp_id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (position_id);

ALTER TABLE redemption_transaction
    ADD CONSTRAINT FK_REDEMPTION_TRANSACTION_ON_EMP FOREIGN KEY (emp_id) REFERENCES bonus_point_account (emp_id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_APPROVER FOREIGN KEY (approver_id) REFERENCES employee (emp_id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES employee (emp_id);

ALTER TABLE transfer_transaction
    ADD CONSTRAINT FK_TRANSFER_TRANSACTION_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES bonus_point_account (emp_id);

ALTER TABLE transfer_transaction
    ADD CONSTRAINT FK_TRANSFER_TRANSACTION_ON_SENDER FOREIGN KEY (sender_id) REFERENCES bonus_point_account (emp_id);