ALTER TABLE campaign
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE campaign
    ADD end_time time WITHOUT TIME ZONE;

ALTER TABLE campaign
    ADD image_url VARCHAR(255);

ALTER TABLE campaign
    ADD start_time time WITHOUT TIME ZONE;

ALTER TABLE campaign
    ADD status VARCHAR(255);

ALTER TABLE campaign
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN campaign_name SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN campaign_type SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN description TYPE VARCHAR(1000) USING (description::VARCHAR(1000));

ALTER TABLE campaign
    ALTER COLUMN end_date SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN start_date SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN campaign_id ADD GENERATED BY DEFAULT AS IDENTITY;