CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255),
    emp_id   BIGINT,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_emp UNIQUE (emp_id);

ALTER TABLE app_user
    ADD CONSTRAINT FK_APP_USER_ON_EMP FOREIGN KEY (emp_id) REFERENCES employee (emp_id);