CREATE TABLE notification
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emp_id          BIGINT                                   NOT NULL,
    title           VARCHAR(255)                             NOT NULL,
    message         TEXT                                     NOT NULL,
    type            VARCHAR(50),
    is_read         BOOLEAN                                  DEFAULT FALSE,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (notification_id)
);

CREATE INDEX idx_notification_emp_id ON notification (emp_id);
CREATE INDEX idx_notification_created_at ON notification (created_at);
CREATE INDEX idx_notification_is_read ON notification (is_read);

